apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-remote-8 
  description: Secure Supply Chain Example for Code Generation Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-remote-8  
    janus-idp.io/tekton: test-remote-8 
    backstage.io/kubernetes-id: test-remote-8 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jdubrick-ai/test-remote-8
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 